apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: critical
  name: critical
spec:
  replicas: 1
  selector:
    matchLabels:
      run: critical
  template:
    metadata:
      labels:
        run: critical
    spec:
      containers:
      - image: mjbright/ckad-demo:999
        name: critical
        ports:
        - containerPort: 80
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: critical
  name: critical
spec:
  replicas: 1
  selector:
    matchLabels:
      run: critical
  template:
    metadata:
      labels:
        run: critical
    spec:
      containers:
      - image: mjbright/ckad-demo:999
        name: critical
        ports:
        - containerPort: 80
