apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: critical
  name: critical
spec:
  replicas: 1
  selector:
    matchLabels:
      run: critical
  template:
    metadata:
      labels:
        run: critical
    spec:
      containers:
      - image: mjbright/ckad-demo:1
        args:
        - /bin/sh
        - -c
        - "sleep 3600 # try ckad-demo:alpine1 has a shell"
        name: critical
        ports:
        - containerPort: 80
